services:
  db:
    image: postgres:15-alpine
    container_name: base_postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=base_pass
      - POSTGRES_DB=base_futbol_db
    ports:
      - "5433:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: